### ISSUE TITLE
Calculating percentages after using gather

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/carpentry-community-assessment-projects#9]
My issue starts in line 74. I want to create a table (or plot) of the respondent's self-reported research domain. They were told to "check all that apply", so the data comes out in columns `Research.Domain.1` through `Research.Domain.16`. Since we used `gather` to pull information from multiple columns into this table, how would I go about calculating the percentage of respondents who selected these options? Right now the tables shows n (number of people who checked that option", but I'd rather show percentages.

Is there a better way to represent this data?

The code I'm referring to is in the software-carpentry-projects folder. It's the post-workshop [RMD](https://github.com/kariljordan/carpentry-community-assessment-projects/blob/master/software-carpentry-projects/analysis-postworkshop.rmd).

**Comment by benmarwick** [comment]
I think it's simplest just to say that for this section the data are 'percentage of responses' rather than percentage of people responding, and note that people could choose more than one option. That's quite intuitive, I think. 

By the way, since we do counts and percentages very often in this report, I've written a little function to save typing:

```
# Makes a table of counts and percentages
tally_and_perc <- function(df, colname, na.rm = FALSE){
  quo_colname <- enquo(colname)

  df %>% 
    group_by(!!quo_colname) %>% 
    tally() %>% 
    filter(if_else(rep(na.rm, nrow(.)),
                  !is.na(!!quo_colname),
                  as.logical(rep(1, nrow(.))))) %>% 
    mutate(`%` = round(n / sum(n) * 100, 1)) 
}
```

Here's the table for research domains:

```
Research_Domain <- 
data %>%
  select(`Research-Domain-1`:`Research-Domain-16`) %>% 
  gather(col, 
         Research_Domain) %>% 
  tally_and_perc(Research_Domain,
                           na.rm = TRUE) %>% 
  arrange(desc(n)) %>% 
  rename(`Research Domain` = Research_Domain)

kable(Research_Domain)
```

|Research Domain                                                                          |   n|    %|
|:----------------------------------------------------------------------------------------|---:|----:|
|Life Sciences (Genetics, genomics, bioinformatics )                                      | 927| 24.9|
|Life Science - Organismal/systems (ecology, botany, zoology, microbiology, neuroscience) | 894| 24.0|
|Planetary sciences (geology, climatology, oceanography, etc.)                            | 245|  6.6|
|Mathematics/statistics                                                                   | 225|  6.0|
|Physics                                                                                  | 217|  5.8|
|Civil, mechanical, chemical, or nuclear engineering                                      | 167|  4.5|
|Medicine and/or Pharmacy                                                                 | 161|  4.3|
|Chemistry                                                                                | 149|  4.0|
|Social sciences                                                                          | 149|  4.0|
|Library and information science                                                          | 121|  3.2|
|Economics/business                                                                       |  98|  2.6|
|Humanities                                                                               |  98|  2.6|
|Psychology                                                                               |  88|  2.4|
|Education                                                                                |  79|  2.1|
|High performance computing                                                               |  79|  2.1|
|Space sciences                                                                           |  33|  0.9|

**Comment by kariljordan** [comment]
This function is super helpful!
